#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
#!/bin/sh

# Forzar la resolución de pantalla completa al iniciar
xrandr --output Virtual-1 --mode 1920x1080 &

pgrep -x sxhkd >/dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
vmware-user-suid-wrapper &
/usr/bin/feh --bg-fill /home/alfredprotocol/Downloads/BatmanRedWall.png &
~/.config/polybar/./launch.sh &
picom &
picom --config ~/.config/picom/picom.conf &
polybar primary -c ~/.config/polybar/current.ini &

bspc config border_width 2
wmname LG3D &
